version: '3'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redis:
    image: redis:7.0.5
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "localhost:9200/_cat/health"]
      interval: 10s
      timeout: 5s
      retries: 10
